language: python
python:
  - "3.6"      # current detault Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
 # - pip install -r requirements_docs.txt
 # - pip install -e
# command to run tests
script:
  - pytest

after_success:
- sphinx-build -b html ./source ./docs
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    python: "3.7"
    branch: master
  github-token: $GH_TOKEN
  local-dir: docs
  committer-from-gh: true
