language: python
python:
  - "3.6"      # current detault Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
#  - "3.8-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
 # - pip install -r requirements_docs.txt
 # - pip install -e
# command to run tests
script:
  - pytest
