environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"



build: none

branches:
  only:
    - master
    #- dev
    #- /release-.*/

#notifications:
#  - provider: Email
#    on_build_success: false
#    on_build_failure: false
#    on_build_status_changed: false

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - python --version
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install tox

test_script:
  - pytest
